"""add completed_at to daily habits

Revision ID: 019e078be26a
Revises: 0a1a91254543
Create Date: 2025-11-21 23:27:40.203809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019e078be26a'
down_revision = '0a1a91254543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_habits', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
